### ISSUE TITLE
Asks users to activate TLC execution statistics

### ISSUE THREAD

**Issue by lemmy** [kelvich/tlaplus_kernel#1]
The Toolbox asks users to activate execution statistics to guide TLC development (see screenshot below).  Please add similar functionality to your extension.  Technically, a file called esc.txt is dropped into ```~/.tlaplus/``` whose first line is either a random identifier, "RANDOM_IDENTIFIER", or "NO_STATISTICS" (see https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/util/ExecutionStatisticsCollector.java).

![Screenshot from 2019-10-21 13-18-55](https://user-images.githubusercontent.com/88777/67240009-618aa200-f405-11e9-840e-05e165b92dd0.png)

Plaintext of the dialog's content is found online too: <https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/util/ExecutionStatisticsCollector.md>. The statistics are publicly available: <https://exec-stats.tlapl.us/tlaplus.csv>.   To report TLA+ Jupyter notebook as TLC's frontend, pass ```-Dtlc2.TLC.ide=tlaplus_jupyter``` as a [Java system property](https://github.com/alygin/vscode-tlaplus/commit/b00b04cb3b488b9d56ef612e43e830a88b628392#diff-93a8016346ecf0c7458cfd4370b5f0bdR94).

@alygin VSCode extension will soon [ask users to opt-in](https://github.com/alygin/vscode-tlaplus/issues/114) too.

-------------

Thanks for sharing TLA+ Jupyter notebooks with the community!  I've already added your [releases](https://github.com/kelvich/tlaplus_jupyter/releases) to the aggregator at <http://wall.tlapl.us>.

**Comment by kelvich** [comment]
Sure, will do.

**Comment by kelvich** [comment]
https://github.com/kelvich/tlaplus_jupyter/pull/5

I've created `--tlc-exec-stats` install option which is set to `share` by default. Also added note about that behavior to README.md. Any other suggestions? May be change wording somewhere?

**Comment by lemmy** [comment]
Have you tested this feature already?  If yes, it seems as if it is broken because so far there have been no exec-stats for "tlaplus_jupyter" (https://github.com/kelvich/tlaplus_jupyter/commit/d64477f1171534a39b815a98b0b84f542a8c7bcb#diff-8f9c6fbaedaf902848b1e9f9e47d60f2R253).

**Comment by kelvich** [comment]
I'm seeing my id (61a7f9a) now in tlaplus.csv now.
Does tla2tools v1.6.0 support tlc2.TLC.ide? I always download that version during install.

**Comment by lemmy** [comment]
No, only recent nightlies report the value of ```tlc2.TLC.ide```.

**Comment by kelvich** [comment]
Okay, I'll then switch download to https://nightly.tlapl.us/dist/tla2tools.jar

**Comment by lemmy** [comment]
Great, but be aware of https://github.com/tlaplus/tlaplus/issues/393#issuecomment-560508473
